services:
    derky.sortablescaptcha.captcha.sortables:
        class: derky\sortablescaptcha\captcha\sortables
        calls:
            - [set_name, [derky.sortablescaptcha.captcha.sortables]]
        arguments:
            - @dbal.conn
            - @cache
            - @config
            - @request
            - @template
            - @user
        tags:
            - { name: captcha.plugins }