services:
    derky.sortablescaptcha.captcha.sortables:
        class: derky\sortablescaptcha\captcha\sortables
        arguments:
            - @dbal.conn
            - @cache
            - @config
            - @template
            - @user
        tags:
            - { name: captcha.plugins }